'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { GameEngine, type GameSnapshot, type GameTheme } from '../src/game/game-engine';
import { PHYSICS, QuantumState, STATE_GLYPHS } from '../src/quantum/physics';

const INITIAL: GameSnapshot = {score:0,highScore:0,lives:3,level:1,dotsLeft:0,observations:0,observer:0,brane:0,braneReady:true,phase:'ready',muted:false,seed:0,entropy:Array(30).fill(.2),ghosts:[QuantumState.SUPERPOSITION,QuantumState.ENTANGLED,QuantumState.TUNNELING,QuantumState.DECOHERED].map(state=>({state,observed:false,timer:0,frightened:false,entropy:state===QuantumState.SUPERPOSITION?.7:.05})),strategy:{threat:0,spawn:{x:13,y:23},defense:50,offense:50,reserves:100,reinforcements:0,telemetrySeq:0}};
const NOTES:Record<QuantumState,string>={[QuantumState.SUPERPOSITION]:'Wavefield diffuse',[QuantumState.ENTANGLED]:'Non-local pair active',[QuantumState.TUNNELING]:'Barrier probability .15',[QuantumState.DECOHERED]:'Classical pursuit'};

function getSeed(){if(typeof window==='undefined')return 271828;const params=new URLSearchParams(location.search);const existing=Number(params.get('seed'));if(Number.isFinite(existing)&&existing>0)return existing>>>0;const seed=Math.floor(Math.random()*99999999)+1;params.set('seed',String(seed));history.replaceState(null,'',`${location.pathname}?${params}`);return seed;}
function getTheme():GameTheme{const saved=typeof window!=='undefined'?localStorage.getItem('pacman4d-theme'):null;return saved==='halloween'||saved==='arcade'?saved:'classic';}
function score(n:number){return String(n).padStart(6,'0');}
function entropyPath(values:number[]){return values.map((v,i)=>`${i?'L':'M'} ${(i/(values.length-1))*320} ${52-v*42}`).join(' ');}

export function QuantumGame(){
  const canvas=useRef<HTMLCanvasElement>(null),engine=useRef<GameEngine|null>(null);const [snap,setSnap]=useState(INITIAL);const [theme,setTheme]=useState<GameTheme>(getTheme);const haunted=theme==='halloween',arcade=theme==='arcade';
  useEffect(()=>{if(!canvas.current)return;const e=new GameEngine(canvas.current,getSeed(),setSnap);engine.current=e;return()=>e.destroy();},[]);
  useEffect(()=>{engine.current?.setTheme(theme);localStorage.setItem('pacman4d-theme',theme);document.title=arcade?'PACMAN 4D — Arcade Mode':haunted?'PACMAN 4D — Halloween House':'PACMAN 4D — On the Observability of Maze-Bound Spectres';},[theme,haunted,arcade]);
  const begin=useCallback(()=>engine.current?.start(),[]); const phaseLabel=arcade?(snap.phase==='paused'?'PAUSED':snap.phase==='gameover'?'GAME OVER':snap.phase==='complete'?'YOU WIN!':'READY!'):haunted?(snap.phase==='paused'?'THE HOUSE IS LISTENING':snap.phase==='gameover'?'LOST BETWEEN THE VEILS':snap.phase==='complete'?'THE HOUSE IS CLEANSED':'ENTER THE HAUNTED HOUSE'):(snap.phase==='paused'?'EXPERIMENT SUSPENDED':snap.phase==='gameover'?'TRIAL TERMINATED':snap.phase==='complete'?'BRANES CLEARED':'ENTER THE OBSERVATION FIELD');
  return <main className={`experiment-shell theme-${theme}`}>
    <header className="paper-header"><div className="issue">{arcade?'1UP':haunted?'NIGHT FILE · VOL. IV':'QME · VOL. IV'}<br/>{arcade?score(snap.score):`${haunted?'HAUNTING':'EXPERIMENT'} ${String(snap.level).padStart(4,'0')}`}</div><div className="masthead"><p>{arcade?'Classic maze chase':haunted?'The Blackthorn Society for Spectral Research':'Institute for Applied Spectral Mechanics'}</p><h1>PACMAN <em>4D</em></h1><h2>{arcade?'Arcade Mode':haunted?'Escape the House Between Worlds':'On the Observability of Maze-Bound Spectres'}</h2></div><div className="header-actions"><div className="theme-picker" aria-label="Game theme">{(['classic','halloween','arcade'] as GameTheme[]).map(value=><button key={value} className={theme===value?'active':''} onClick={()=>setTheme(value)} aria-pressed={theme===value}>{value==='classic'?'QUANTUM':value.toUpperCase()}</button>)}</div><button className="icon-button" onClick={()=>engine.current?.toggleMute()} aria-label={snap.muted?'Unmute audio':'Mute audio'}>{snap.muted?'SOUND OFF':'SOUND ON'}</button><span className="status-dot">{snap.phase==='playing'?(arcade?'PLAY':haunted?'HAUNTED':'LIVE'):(arcade?'READY':haunted?'DORMANT':'STANDBY')}</span></div></header>
    <section className="workspace"><div className="game-column"><div className="canvas-frame">
      <div className="frame-label"><span>{arcade?'PLAYER ONE':haunted?'THE BLACKTHORN HOUSE · MIDNIGHT FLOORPLAN':'FIG. 1 · PRIMARY OBSERVATION CHAMBER'}</span><span className={snap.brane?'brane-b':''}>{arcade?`HIGH SCORE ${score(snap.highScore)}`:`${haunted?'VEIL':'BRANE'} ${haunted?(snap.brane?'BEYOND':'MORTAL'):(snap.brane?'B':'A')}`}</span></div>{arcade&&<div className="arcade-hud"><span>1UP <b>{score(snap.score)}</b></span><span>{'● '.repeat(snap.lives)||'—'}</span></div>}<canvas ref={canvas} aria-label={`Playable ${arcade?'arcade':haunted?'Halloween':'quantum'} Pacman maze. Use arrow keys or WASD to move.`}/>
      {snap.phase!=='playing'&&<div className="start-card"><span className="eyebrow">{arcade?'PLAYER ONE':haunted?(snap.phase==='ready'?'THE HOUSE IS AWAKE':snap.phase==='paused'?'THE CLOCK HAS STOPPED':snap.phase==='complete'?'DAWN HAS BROKEN':'THE VEIL CLAIMED YOU'):(snap.phase==='ready'?'INITIALIZE EXPERIMENT':snap.phase==='paused'?'FIELD HELD IN STASIS':snap.phase==='complete'?'EXPERIMENT REPRODUCED':'MEASUREMENT FAILURE')}</span><strong>{phaseLabel}</strong><p>{arcade?'Eat every dot and avoid the ghosts.':snap.phase==='ready'?(haunted?"Cross the threshold as a bedsheet ghost. Collect pumpkins and enter the spectral house.":"Your gaze collapses a spectre's wavefunction. Certainty makes it faster."):snap.phase==='paused'?(haunted?'The halls wait in unnatural silence.':'All probabilities are provisionally conserved.'):snap.phase==='complete'?`Final result ${score(snap.score)}. Both ${haunted?'veils have been cleansed':'branes have been resolved'}.`:`Result ${score(snap.score)} · Record ${score(snap.highScore)}`}</p><button type="button" onClick={begin}>{arcade?(snap.phase==='paused'?'RESUME':'START GAME'):snap.phase==='paused'?(haunted?'Return to the halls':'Resume trial'):snap.phase==='ready'?(haunted?'Enter the house':'Begin trial'):(haunted?'Try another night':'Repeat experiment')} <kbd>Enter</kbd></button></div>}
      <div className="corner-mark tl"/><div className="corner-mark tr"/><div className="corner-mark bl"/><div className="corner-mark br"/>
      <div className="mobile-pad" aria-label="Touch controls"><button onPointerDown={()=>engine.current?.setDirection('up')}>↑</button><button onPointerDown={()=>engine.current?.setDirection('left')}>←</button><button onPointerDown={()=>engine.current?.setDirection('down')}>↓</button><button onPointerDown={()=>engine.current?.setDirection('right')}>→</button><button className="phase-key" onPointerDown={()=>engine.current?.shiftBrane()}>Φ</button></div>
    </div><div className="controls-strip">{arcade?<><span><kbd>↑←↓→</kbd> MOVE</span><span><kbd>P</kbd> PAUSE</span><span className="seed"><b>{snap.dotsLeft}</b> DOTS LEFT</span></>:<><span><kbd>↑←↓→</kbd> LOCOMOTION</span><span><kbd>SPACE</kbd> PHASE BRANE</span><span><kbd>P</kbd> SUSPEND</span><span className="seed">SEED <b>Q-{String(snap.seed).padStart(8,'0')}</b></span></>}</div></div>
    <aside className="telemetry"><div className="console-heading"><span>REAL-TIME TELEMETRY</span><i>04 SPECIMENS</i></div>
      <div className="trial-grid"><div><small>SCORE / RECORD</small><strong>{score(snap.score)}</strong><em>{score(snap.highScore)}</em></div><div><small>LIVES / TRIALS</small><strong>{'● '.repeat(snap.lives)||'—'}</strong><em>{snap.dotsLeft} photons</em></div></div>
      <section className="observer-panel"><div className="panel-title"><span>OBSERVER COHERENCE</span><b>{Math.round(snap.observer)}%</b></div><div className="meter"><i style={{width:`${snap.observer}%`}}/></div><div className="observer-meta"><span>OBSERVATIONS {String(snap.observations).padStart(3,'0')}</span><span>{snap.ghosts.some(g=>g.observed)?'LINE OF SIGHT ACTIVE':'FIELD UNOBSERVED'}</span></div><button className={`brane-switch ${snap.braneReady?'ready':''}`} onClick={()=>engine.current?.shiftBrane()}><span>ACTIVE MANIFOLD</span><b>{snap.brane?'BRANE B':'BRANE A'}</b><i>{snap.braneReady?'SHIFT READY':'PHASING…'}</i></button></section>
      <section className="optimizer-panel"><div className="panel-title"><span>TACTICAL OPTIMIZER</span><b>JSON #{String(snap.strategy.telemetrySeq).padStart(4,'0')}</b></div><div className="threat-readout"><span>TRAJECTORY THREAT</span><strong>{String(snap.strategy.threat).padStart(2,'0')}</strong><i className={snap.strategy.threat>60?'critical':snap.strategy.threat>30?'elevated':''}>{snap.strategy.threat>60?'CRITICAL':snap.strategy.threat>30?'ELEVATED':'NOMINAL'}</i></div><div className="allocation"><div><span>DEFENSE</span><b>{snap.strategy.defense}%</b><i style={{width:`${snap.strategy.defense}%`}}/></div><div><span>OFFENSE</span><b>{snap.strategy.offense}%</b><i style={{width:`${snap.strategy.offense}%`}}/></div></div><div className="optimizer-meta"><span>SAFE SPAWN [{snap.strategy.spawn.x},{snap.strategy.spawn.y}]</span><span>{snap.strategy.reinforcements} LATTICES</span><span>{snap.strategy.reserves} RESERVE</span></div></section>
      <section className="specimens"><div className="panel-title"><span>GHOST WAVEFUNCTIONS</span><b>STATE</b></div>{snap.ghosts.map((g,i)=>{const certainty=g.state===QuantumState.SUPERPOSITION?Math.round((1-g.entropy)*100):g.state===QuantumState.DECOHERED?100:72;return <article key={i} className={`specimen s${i} ${g.observed?'is-observed':''} ${g.frightened?'is-frightened':''}`}><div className="state-glyph">{STATE_GLYPHS[g.state]}</div><div className="state-copy"><strong>{g.frightened?'FRIGHTENED':g.state}</strong><span>{g.observed?'Observed · collapse pressure':NOTES[g.state]}</span><div className="microbar"><i style={{width:`${g.state===QuantumState.DECOHERED&&g.timer?100-g.timer/PHYSICS.unobservedDecayMs*100:certainty}%`}}/></div></div><b>{certainty}%</b></article>})}</section>
      <section className="wave-panel"><div className="panel-title"><span>POSITION ENTROPY</span><b>|ψ|²</b></div><svg viewBox="0 0 320 60" role="img" aria-label="Live probability waveform"><path d={entropyPath(snap.entropy)}/><line x1="0" x2="320" y1="52" y2="52"/></svg><p>Nearest specimen entropy · temporal sample n = {snap.entropy.length}</p></section>
      <blockquote>“That which is not observed is not obliged to choose a corridor.”<span>— Lab memorandum, 1957</span></blockquote>
    </aside></section>
  </main>;
}
