'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { GameEngine, type GameSnapshot } from '../src/game/game-engine';
import { PHYSICS, QuantumState, STATE_GLYPHS } from '../src/quantum/physics';

const INITIAL: GameSnapshot = {score:0,highScore:0,lives:3,level:1,dotsLeft:0,observations:0,observer:0,brane:0,braneReady:true,phase:'ready',muted:false,seed:0,entropy:Array(30).fill(.2),ghosts:[QuantumState.SUPERPOSITION,QuantumState.ENTANGLED,QuantumState.TUNNELING,QuantumState.DECOHERED].map(state=>({state,observed:false,timer:0,frightened:false,entropy:state===QuantumState.SUPERPOSITION?.7:.05})),strategy:{threat:0,spawn:{x:13,y:23},defense:50,offense:50,reserves:100,reinforcements:0,telemetrySeq:0}};
const NOTES:Record<QuantumState,string>={[QuantumState.SUPERPOSITION]:'Wavefield diffuse',[QuantumState.ENTANGLED]:'Non-local pair active',[QuantumState.TUNNELING]:'Barrier probability .15',[QuantumState.DECOHERED]:'Classical pursuit'};

function getSeed(){if(typeof window==='undefined')return 271828;const params=new URLSearchParams(location.search);const existing=Number(params.get('seed'));if(Number.isFinite(existing)&&existing>0)return existing>>>0;const seed=Math.floor(Math.random()*99999999)+1;params.set('seed',String(seed));history.replaceState(null,'',`${location.pathname}?${params}`);return seed;}
function score(n:number){return String(n).padStart(6,'0');}
function entropyPath(values:number[]){return values.map((v,i)=>`${i?'L':'M'} ${(i/(values.length-1))*320} ${52-v*42}`).join(' ');}

export function QuantumGame(){
  const canvas=useRef<HTMLCanvasElement>(null),engine=useRef<GameEngine|null>(null);const [snap,setSnap]=useState(INITIAL);
  useEffect(()=>{if(!canvas.current)return;const e=new GameEngine(canvas.current,getSeed(),setSnap);engine.current=e;return()=>e.destroy();},[]);
  const begin=useCallback(()=>engine.current?.start(),[]); const phaseLabel=snap.phase==='paused'?'THE HOUSE IS LISTENING':snap.phase==='gameover'?'LOST BETWEEN THE VEILS':snap.phase==='complete'?'THE HOUSE IS CLEANSED':'ENTER THE HAUNTED HOUSE';
  return <main className="experiment-shell">
    <header className="paper-header"><div className="issue">NIGHT FILE · VOL. IV<br/>HAUNTING {String(snap.level).padStart(4,'0')}</div><div className="masthead"><p>The Blackthorn Society for Spectral Research</p><h1>PACMAN <em>4D</em></h1><h2>Escape the House Between Worlds</h2></div><div className="header-actions"><button className="icon-button" onClick={()=>engine.current?.toggleMute()} aria-label={snap.muted?'Unmute audio':'Mute audio'}>{snap.muted?'SOUND OFF':'SOUND ON'}</button><span className="status-dot">{snap.phase==='playing'?'HAUNTED':'DORMANT'}</span></div></header>
    <section className="workspace"><div className="game-column"><div className="canvas-frame">
      <div className="frame-label"><span>THE BLACKTHORN HOUSE · MIDNIGHT FLOORPLAN</span><span className={snap.brane?'brane-b':''}>VEIL {snap.brane?'BEYOND':'MORTAL'}</span></div><canvas ref={canvas} aria-label="Playable haunted Pacman quantum maze. Use arrow keys or WASD to move."/>
      {snap.phase!=='playing'&&<div className="start-card"><span className="eyebrow">{snap.phase==='ready'?'THE HOUSE IS AWAKE':snap.phase==='paused'?'THE CLOCK HAS STOPPED':snap.phase==='complete'?'DAWN HAS BROKEN':'THE VEIL CLAIMED YOU'}</span><strong>{phaseLabel}</strong><p>{snap.phase==='ready'?"Cross the spectral threshold. Your gaze collapses a ghost's wavefunction—and makes it faster.":snap.phase==='paused'?'The halls wait in unnatural silence.':snap.phase==='complete'?`Final result ${score(snap.score)}. Both veils have been cleansed.`:`Result ${score(snap.score)} · Record ${score(snap.highScore)}`}</p><button type="button" onClick={begin}>{snap.phase==='paused'?'Return to the halls':snap.phase==='ready'?'Enter the house':'Try another night'} <kbd>Enter</kbd></button></div>}
      <div className="corner-mark tl"/><div className="corner-mark tr"/><div className="corner-mark bl"/><div className="corner-mark br"/>
      <div className="mobile-pad" aria-label="Touch controls"><button onPointerDown={()=>engine.current?.setDirection('up')}>↑</button><button onPointerDown={()=>engine.current?.setDirection('left')}>←</button><button onPointerDown={()=>engine.current?.setDirection('down')}>↓</button><button onPointerDown={()=>engine.current?.setDirection('right')}>→</button><button className="phase-key" onPointerDown={()=>engine.current?.shiftBrane()}>Φ</button></div>
    </div><div className="controls-strip"><span><kbd>↑←↓→</kbd> LOCOMOTION</span><span><kbd>SPACE</kbd> PHASE BRANE</span><span><kbd>P</kbd> SUSPEND</span><span className="seed">SEED <b>Q-{String(snap.seed).padStart(8,'0')}</b></span></div></div>
    <aside className="telemetry"><div className="console-heading"><span>REAL-TIME TELEMETRY</span><i>04 SPECIMENS</i></div>
      <div className="trial-grid"><div><small>SCORE / RECORD</small><strong>{score(snap.score)}</strong><em>{score(snap.highScore)}</em></div><div><small>LIVES / TRIALS</small><strong>{'● '.repeat(snap.lives)||'—'}</strong><em>{snap.dotsLeft} photons</em></div></div>
      <section className="observer-panel"><div className="panel-title"><span>OBSERVER COHERENCE</span><b>{Math.round(snap.observer)}%</b></div><div className="meter"><i style={{width:`${snap.observer}%`}}/></div><div className="observer-meta"><span>OBSERVATIONS {String(snap.observations).padStart(3,'0')}</span><span>{snap.ghosts.some(g=>g.observed)?'LINE OF SIGHT ACTIVE':'FIELD UNOBSERVED'}</span></div><button className={`brane-switch ${snap.braneReady?'ready':''}`} onClick={()=>engine.current?.shiftBrane()}><span>ACTIVE MANIFOLD</span><b>{snap.brane?'BRANE B':'BRANE A'}</b><i>{snap.braneReady?'SHIFT READY':'PHASING…'}</i></button></section>
      <section className="optimizer-panel"><div className="panel-title"><span>TACTICAL OPTIMIZER</span><b>JSON #{String(snap.strategy.telemetrySeq).padStart(4,'0')}</b></div><div className="threat-readout"><span>TRAJECTORY THREAT</span><strong>{String(snap.strategy.threat).padStart(2,'0')}</strong><i className={snap.strategy.threat>60?'critical':snap.strategy.threat>30?'elevated':''}>{snap.strategy.threat>60?'CRITICAL':snap.strategy.threat>30?'ELEVATED':'NOMINAL'}</i></div><div className="allocation"><div><span>DEFENSE</span><b>{snap.strategy.defense}%</b><i style={{width:`${snap.strategy.defense}%`}}/></div><div><span>OFFENSE</span><b>{snap.strategy.offense}%</b><i style={{width:`${snap.strategy.offense}%`}}/></div></div><div className="optimizer-meta"><span>SAFE SPAWN [{snap.strategy.spawn.x},{snap.strategy.spawn.y}]</span><span>{snap.strategy.reinforcements} LATTICES</span><span>{snap.strategy.reserves} RESERVE</span></div></section>
      <section className="specimens"><div className="panel-title"><span>GHOST WAVEFUNCTIONS</span><b>STATE</b></div>{snap.ghosts.map((g,i)=>{const certainty=g.state===QuantumState.SUPERPOSITION?Math.round((1-g.entropy)*100):g.state===QuantumState.DECOHERED?100:72;return <article key={i} className={`specimen s${i} ${g.observed?'is-observed':''} ${g.frightened?'is-frightened':''}`}><div className="state-glyph">{STATE_GLYPHS[g.state]}</div><div className="state-copy"><strong>{g.frightened?'FRIGHTENED':g.state}</strong><span>{g.observed?'Observed · collapse pressure':NOTES[g.state]}</span><div className="microbar"><i style={{width:`${g.state===QuantumState.DECOHERED&&g.timer?100-g.timer/PHYSICS.unobservedDecayMs*100:certainty}%`}}/></div></div><b>{certainty}%</b></article>})}</section>
      <section className="wave-panel"><div className="panel-title"><span>POSITION ENTROPY</span><b>|ψ|²</b></div><svg viewBox="0 0 320 60" role="img" aria-label="Live probability waveform"><path d={entropyPath(snap.entropy)}/><line x1="0" x2="320" y1="52" y2="52"/></svg><p>Nearest specimen entropy · temporal sample n = {snap.entropy.length}</p></section>
      <blockquote>“That which is not observed is not obliged to choose a corridor.”<span>— Lab memorandum, 1957</span></blockquote>
    </aside></section>
  </main>;
}
